### ISSUE TITLE
Wrong collision detection

### ISSUE THREAD

**Issue by PIlin** [PIlin/NXEngine-iOS#24]
1. Sometimes, it is possible to get into the ground. Most times, it's possible to get into the slope block when you move horizontally using booster.
2. When jump on the block from the lower level, Quote is placed 1 pixel into the block.

**Comment by octopuserectus** [comment]
I was able to go through diagonal block right into it, just by walking over it, jumped and did not stuck. Tried to reproduce but no luck.
