### ISSUE TITLE
Cannot Compile in Xcode 5

### ISSUE THREAD

**Issue by Kfeavel** [PIlin/NXEngine-iOS#40]
Every time Xcode 5 compiles NXEngine-iOS, I get an error in SDL:
NXEngine-iOS/iOS/deps/SDL/src/render/opengles2/SDL_gles2funcs.h:35:1: Assigning to 'void (_)(GLuint, GLsizei, const char *_, const GLint _)' from incompatible type 'void (GLuint, GLsizei, const GLchar *const *, const GLint *)': type mismatch at 3rd parameter ('const char *_' vs 'const GLchar *const *' (aka 'const char *const *'))

The code is at line 35 in SDL_gles2funcs.h:
SDL_PROC(void, glShaderSource, (GLuint, GLsizei, const char **, const GLint *))

Just  as a side note: It compiles without any errors in Xcode 4.6. Only 5.0 & 5.1 create errors.

**Comment by PIlin** [comment]
Thanks for the report. Unfortunately I don't have an access to the Mac computer so I can't check it right now. I will try to deploy OSX on VirtualBox next week and to check this issue.

**Comment by Kfeavel** [comment]
Thank you Pllin!

**Comment by PIlin** [comment]
@DinnerBing try to redeploy SDL, SDL_ttf, libfreetype again using deploy.sh. Probably, you'll better to remove them before running deploy.sh.

**Comment by Kfeavel** [comment]
Thanks, will do. I'll let you know how it goes.

**Comment by Kfeavel** [comment]
It indeed worked! Thanks @PIlin !

**Comment by PIlin** [comment]
That's cool, thanks for testing.
