### ISSUE TITLE
Crash on iOS 8/9 Beta SDK

### ISSUE THREAD

**Issue by Kfeavel** [PIlin/NXEngine-iOS#42]
The application builds without error (Xcode 6.4 throws about 20 or so warnings) but will crash upon launching the application. I'll post the crash log and rogue code here in a bit.

**Comment by PIlin** [comment]
I don't really have a way to even check it now. But still, if you would like to fix the problem - you're welcome.

**Comment by Kfeavel** [comment]
I've gotten it to load all the way until it hits sound, where I receive an error:

```
LoadFXCache: audio cache ./sndcache.pcm not exist
error << LoadSoundFX: failed open: './sndcache.pcm' >> 
error << fatal: 'Failed to initialize sound.' >> 
```

Do you remember where sndcache.pcm was supposed to be located? I had to redo some of the sandbox and file location code.

Edit: Also, apparently touch controls will need work too. They don't respond anymore...

**Comment by PIlin** [comment]
File was automatically created, see https://github.com/PIlin/NXEngine-iOS/blob/master/sound/pxt.cpp#L850
Originally, it just went to the current folder, I think it was bin/. 
In my version, it should go to the caches folder, which is platform dependent, see https://github.com/PIlin/NXEngine-iOS/blob/master/platform/platform.cpp#L113

**Comment by Kfeavel** [comment]
Figured out what the problem is. The iOS application structure is no longer the same as in iOS 4-7. It changed with iOS 8 when they implemented security measures and shared folders, so the Documents, Cache, and Library folders are no longer located in the same directory as the executable. So I'm going to see if the cache can be pre-compiled and stored in the game_resources folder. Then we just have to fix the controls not responding.

**Comment by Kfeavel** [comment]
Got audio working! Everything is now dumped to ./game_resources instead of ../Documents/ and ../Library/Cache/
